version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: DockerFile
    ports:
    - "3000:3000"
  node:
    build:
      context: .
      dockerfile: node/DockerFile

#  redis:
#      image: redis
#  db:
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: root
#  adminer:
#    image: adminer
#    ports:
#    - "3000:3000"