version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: html/DockerFile
    ports:
    - "3000:3000"
  node:
    container_name: node
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ./:/home/node/app



#  redis:
#      image: redis
#  db:
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: root
#  adminer:
#    image: adminer
#    ports:
#    - "3000:3000"