version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: html/DockerFile
    ports:
    - "3000:3000"
  node:
    container_name: node
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ./:/home/node/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=db
      - DB_USER=user
      - DB_PASSWORD=root
      - REDIS_HOST=redis

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
      PGDATA: /pgdata

    restart: on-failure

  redis:
    container_name: redis
    image: redis
